# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: tensorboard/
  name: null
  #name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
  version: null
  log_graph: False
  default_hp_metric: True
  prefix: ""
