_target_: nrslib.src.models.nrms.NRMS
lr: 0.0001
word_embedding_dim: 300
num_attention_heads: 15
query_vector_dim: 200
dropout_probability: 0.2
num_words: 50506
pretrained_word_embedding: ${data_dir}/MIND/train/pretrained_word_embedding.npy
metrics:
  valid:
    accuracy:
      _target_: torchmetrics.Accuracy
    ndcg10:
      _target_: torchmetrics.RetrievalNormalizedDCG
      k: 10
    auroc:
      _target_: torchmetrics.AUROC
    mae:
      _target_: torchmetrics.MeanAbsoluteError
  test:
    accuracy:
      _target_: torchmetrics.Accuracy
    ndcg10:
      _target_: torchmetrics.RetrievalNormalizedDCG
      k: 10
    auroc:
      _target_: torchmetrics.AUROC
    mae:
      _target_: torchmetrics.MeanAbsoluteError